import type { Prospect, Signal } from './types.ts'

/** ISO timestamp `days` days before now, at `hour` local time. */
function daysAgo(days: number, hour = 9): string {
  const date = new Date(Date.now() - days * 86_400_000)
  date.setHours(hour, 0, 0, 0)
  return date.toISOString()
}

function daysAhead(days: number, hour = 10): string {
  return daysAgo(-days, hour)
}

/**
 * Fictional staffing agencies and the signals that put them in the pipeline.
 * Phone numbers are placeholders: replace one with your own number to receive
 * a real outbound call.
 */
export function seedData(): { prospects: Prospect[]; signals: Signal[] } {
  const prospects: Prospect[] = [
    {
      id: 'p-flexo',
      company: 'Flexo RH',
      city: 'Lyon',
      headcount: '3 agences · ~180 intérimaires/mois',
      contact: { firstName: 'Claire', lastName: 'Bonnet', role: 'DAF', phone: '+33612345601', email: 'claire.bonnet@flexo-rh.example' },
      estimatedUnpaidKeur: 210,
      stage: 'a_appeler',
      angle: 'Votre post sur les clients qui règlent à 90 jours a fait réagir : je suis l’agent qui les rappellerait à J+3, avec un ton qui préserve la relation.',
      calls: [],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      id: 'p-kap',
      company: 'Kap Intérim',
      city: 'Lille',
      headcount: '5 agences · ~420 intérimaires/mois',
      contact: { firstName: 'Julien', lastName: 'Vasseur', role: 'Directeur général', phone: '+33612345602' },
      estimatedUnpaidKeur: 480,
      stage: 'nouveau',
      angle: 'Vos comptes 2025 montrent 78 jours de DSO contre 52 pour le secteur : chaque jour gagné, c’est environ 13 k€ de trésorerie.',
      calls: [],
      createdAt: daysAgo(12),
      updatedAt: daysAgo(12),
    },
    {
      id: 'p-horizon',
      company: 'Horizon Emploi',
      city: 'Bordeaux',
      headcount: '2 agences · ~95 intérimaires/mois',
      contact: { firstName: 'Sophie', lastName: 'Marchand', role: 'Gérante', phone: '+33612345603' },
      stage: 'a_appeler',
      angle: 'Un de vos donneurs d’ordres BTP vient d’entrer en redressement : on peut relancer vos autres clients avant que le trou de trésorerie ne se creuse.',
      calls: [],
      createdAt: daysAgo(4),
      updatedAt: daysAgo(3),
    },
    {
      id: 'p-nova',
      company: 'Nova Travail Temporaire',
      city: 'Marseille',
      headcount: '4 agences · ~300 intérimaires/mois',
      contact: { firstName: 'Karim', lastName: 'Benali', role: 'DAF', phone: '+33612345604' },
      estimatedUnpaidKeur: 150,
      stage: 'a_rappeler',
      angle: 'Vous regardez l’affacturage : relancer plus tôt et mieux coûte dix fois moins cher que de céder vos créances.',
      nextCallAt: daysAhead(1, 10),
      calls: [
        {
          id: 'call-nova-1',
          mode: 'telephone',
          startedAt: daysAgo(1, 11),
          endedAt: daysAgo(1, 11),
          status: 'termine',
          outcome: 'rappel',
          callbackAt: daysAhead(1, 10),
          summary: 'Karim était en clôture mensuelle. Intéressé par le principe, demande à être rappelé demain à 10 h.',
          transcript: [
            { role: 'agent', text: 'Bonjour Karim, ici Léa, l’assistante vocale d’Échéance. Je suis une IA, j’appelle en deux minutes au sujet des retards de paiement de vos clients : c’est le bon moment ?' },
            { role: 'user', text: 'Pas vraiment, je suis en clôture. C’est à quel sujet exactement ?' },
            { role: 'agent', text: 'Vous entendez en ce moment ce que vos clients entendraient : un rappel poli à J+3, sans pression. Je peux vous rappeler demain à 10 h pour vous montrer ça en vrai ?' },
            { role: 'user', text: 'Demain 10 h, d’accord.' },
          ],
        },
      ],
      createdAt: daysAgo(20),
      updatedAt: daysAgo(1),
    },
    {
      id: 'p-alliance',
      company: 'Alliance Intérim Sud',
      city: 'Toulouse',
      headcount: '6 agences · ~520 intérimaires/mois',
      contact: { firstName: 'Nathalie', lastName: 'Roux', role: 'Credit manager', phone: '+33612345605', email: 'n.roux@alliance-interim.example' },
      estimatedUnpaidKeur: 620,
      stage: 'rdv_pris',
      angle: 'Vous recrutez un comptable clients pour le lettrage et la relance : l’agent absorbe la relance, votre recrue garde le lettrage et les litiges.',
      calls: [
        {
          id: 'call-alliance-1',
          mode: 'telephone',
          startedAt: daysAgo(3, 14),
          endedAt: daysAgo(3, 14),
          status: 'termine',
          outcome: 'rdv',
          meetingSlot: 'jeudi 14 h 30',
          summary: 'Nathalie gère 1 200 factures/mois avec deux personnes. Veut voir l’escalade vers un humain et l’intégration Sage. RDV jeudi 14 h 30.',
          transcript: [
            { role: 'agent', text: 'Bonjour Nathalie, ici Léa, l’assistante vocale d’Échéance. Je suis une IA. Vous recrutez un comptable clients : je peux vous montrer en deux minutes comment on relance vos grands comptes sans les braquer ?' },
            { role: 'user', text: 'Allez-y, mais je vous préviens, nos clients aéro sont sensibles.' },
            { role: 'agent', text: 'Justement. Écoutez ce que recevrait votre client : « Bonjour, je vous appelle de la part d’Alliance Intérim au sujet de la facture 4512 de 4 300 euros, échue depuis 45 jours. Est-ce qu’un règlement est prévu cette semaine ? » Si la personne conteste, je note le motif et je passe la main à votre équipe.' },
            { role: 'user', text: 'Et l’intégration avec Sage ?' },
            { role: 'agent', text: 'On lit les factures échues dans Sage et on y écrit les promesses de règlement. Je vous propose 20 minutes avec Alexandre pour le voir sur vos données : jeudi 14 h 30, ça vous va ?' },
            { role: 'user', text: 'Jeudi 14 h 30, c’est bon.' },
          ],
        },
      ],
      createdAt: daysAgo(30),
      updatedAt: daysAgo(3),
    },
    {
      id: 'p-vallees',
      company: 'Intérim des Vallées',
      city: 'Grenoble',
      headcount: '1 agence · ~60 intérimaires/mois',
      contact: { firstName: 'Marc', lastName: 'Delorme', role: 'Gérant', phone: '+33612345606' },
      stage: 'nouveau',
      angle: 'Vous avez téléchargé notre guide DSO hier : la relance du soir, c’est exactement ce que l’agent prend en charge.',
      calls: [],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: 'p-sesame',
      company: 'Sésame RH',
      city: 'Rennes',
      headcount: '2 agences · ~140 intérimaires/mois',
      contact: { firstName: 'Émilie', lastName: 'Tanguy', role: 'Directrice administrative', phone: '+33612345607' },
      estimatedUnpaidKeur: 95,
      stage: 'a_appeler',
      angle: 'Nathalie Roux, d’Alliance Intérim, m’a dit que vous aviez le même problème qu’elle avec les grands comptes de l’agro.',
      calls: [],
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
    {
      id: 'p-batiflex',
      company: 'Batiflex',
      city: 'Strasbourg',
      headcount: '3 agences · ~210 intérimaires/mois, BTP',
      contact: { firstName: 'Thomas', lastName: 'Keller', role: 'Dirigeant', phone: '+33612345608' },
      stage: 'pas_interesse',
      angle: 'Le BTP paie à 75 jours : on relance vos chantiers dès J+3 sans que vos conducteurs de travaux aient à décrocher.',
      calls: [
        {
          id: 'call-batiflex-1',
          mode: 'telephone',
          startedAt: daysAgo(8, 16),
          endedAt: daysAgo(8, 16),
          status: 'termine',
          outcome: 'refus',
          summary: 'Thomas a déjà un cabinet de recouvrement au forfait et ne veut rien changer avant 2027. À recycler dans 90 jours.',
          transcript: [
            { role: 'agent', text: 'Bonjour Thomas, ici Léa, l’assistante vocale d’Échéance. Je suis une IA. Je vous appelle au sujet des délais de paiement dans le BTP : vous avez deux minutes ?' },
            { role: 'user', text: 'On a déjà un cabinet pour ça, et on ne change rien avant l’an prochain.' },
            { role: 'agent', text: 'Compris, je n’insiste pas. Merci Thomas, bonne journée.' },
          ],
        },
      ],
      createdAt: daysAgo(40),
      updatedAt: daysAgo(8),
    },
  ]

  const signals: Signal[] = [
    {
      id: 's-flexo-linkedin',
      prospectId: 'p-flexo',
      source: 'linkedin',
      title: '« Le BFR d’une boîte d’intérim, c’est un sport de combat »',
      excerpt: 'Encore un client grand compte qui règle à 90 jours. On avance 180 paies chaque vendredi, eux ils paient quand ils veulent. #interim #BFR',
      url: 'https://www.linkedin.com/',
      detectedAt: daysAgo(2, 8),
      weight: 5,
      status: 'qualifie',
    },
    {
      id: 's-flexo-job',
      prospectId: 'p-flexo',
      source: 'offre_emploi',
      title: 'Chargé(e) de recouvrement H/F – CDD 6 mois',
      excerpt: 'Relance téléphonique et écrite des clients, suivi des litiges, reporting DSO hebdomadaire.',
      detectedAt: daysAgo(9),
      weight: 4,
      status: 'qualifie',
    },
    {
      id: 's-kap-pappers',
      prospectId: 'p-kap',
      source: 'pappers',
      title: 'Créances clients +32 % sur l’exercice, DSO estimé 78 j (secteur : 52 j)',
      excerpt: 'Comptes 2025 déposés le mois dernier. Chiffre d’affaires +18 %, créances clients +32 %, trésorerie nette en baisse.',
      detectedAt: daysAgo(12),
      weight: 4,
      status: 'nouveau',
    },
    {
      id: 's-kap-presse',
      prospectId: 'p-kap',
      source: 'presse',
      title: 'Kap Intérim ouvre deux agences dans le Nord',
      excerpt: 'Le groupe lillois vise 600 intérimaires/mois d’ici la fin de l’année.',
      detectedAt: daysAgo(25),
      weight: 3,
      status: 'nouveau',
    },
    {
      id: 's-horizon-bodacc',
      prospectId: 'p-horizon',
      source: 'bodacc',
      title: 'Bâti Sud-Ouest (client) placé en redressement judiciaire',
      excerpt: 'Jugement d’ouverture publié cette semaine. Horizon Emploi cite ce donneur d’ordres BTP comme principal client sur son site.',
      detectedAt: daysAgo(4),
      weight: 3,
      status: 'qualifie',
    },
    {
      id: 's-nova-avis',
      prospectId: 'p-nova',
      source: 'avis',
      title: 'Avis Indeed : « paie versée avec 10 jours de retard deux mois de suite »',
      excerpt: 'Trois avis d’intérimaires en six semaines citent des paies en retard : symptôme classique d’une trésorerie tendue.',
      detectedAt: daysAgo(15),
      weight: 2,
      status: 'qualifie',
    },
    {
      id: 's-nova-linkedin',
      prospectId: 'p-nova',
      source: 'linkedin',
      title: 'Le DAF a commenté un post sur l’affacturage : « on y pense sérieusement »',
      excerpt: 'Commentaire sous un post d’un factor : « on y pense sérieusement, mais 2 % du CA ça pique ».',
      url: 'https://www.linkedin.com/',
      detectedAt: daysAgo(20),
      weight: 3,
      status: 'qualifie',
    },
    {
      id: 's-alliance-job',
      prospectId: 'p-alliance',
      source: 'offre_emploi',
      title: 'Comptable clients – relance et lettrage (CDI)',
      excerpt: 'Portefeuille de 1 200 factures/mois, relance des grands comptes aéronautiques, lettrage sous Sage.',
      detectedAt: daysAgo(18),
      weight: 4,
      status: 'qualifie',
    },
    {
      id: 's-alliance-presse',
      prospectId: 'p-alliance',
      source: 'presse',
      title: 'Levée de 2 M€ pour accélérer dans l’aéronautique',
      excerpt: 'La croissance du volume délégué tend mécaniquement le BFR : plus de paies avancées avant encaissement.',
      detectedAt: daysAgo(30),
      weight: 3,
      status: 'qualifie',
    },
    {
      id: 's-vallees-inbound',
      prospectId: 'p-vallees',
      source: 'inbound',
      title: 'A téléchargé le guide « Réduire son DSO de 15 jours sans perdre un client »',
      excerpt: 'Champ commentaire du formulaire : « on est une petite agence, c’est moi qui relance le soir ».',
      detectedAt: daysAgo(1, 21),
      weight: 4,
      status: 'nouveau',
    },
    {
      id: 's-sesame-reco',
      prospectId: 'p-sesame',
      source: 'recommandation',
      title: 'Recommandée par Alliance Intérim Sud (cliente)',
      excerpt: '« Émilie a le même problème que nous avec les grands comptes de l’agro. Dites-lui que vous venez de ma part. »',
      detectedAt: daysAgo(3),
      weight: 5,
      status: 'qualifie',
    },
    {
      id: 's-batiflex-linkedin',
      prospectId: 'p-batiflex',
      source: 'linkedin',
      title: 'A aimé un post « Le BTP paie à 75 jours »',
      excerpt: 'Signal faible : réaction sans commentaire.',
      url: 'https://www.linkedin.com/',
      detectedAt: daysAgo(40),
      weight: 3,
      status: 'qualifie',
    },
  ]

  return { prospects, signals }
}
